package app.spellscroll.task;

import org.gradle.api.DefaultTask;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.*;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;

@CacheableTask
public abstract class GenerateBuildConfigTask extends DefaultTask
{
    @Input
    public abstract Property<String> getPluginId();

    @Input
    public abstract Property<String> getPluginName();

    @Input
    public abstract Property<String> getPluginVersion();

    @Input
    public abstract Property<String> getProjectGroup();

    /**
     * Declaring the build file as an input ensures regeneration whenever it changes.
     */
    @InputFile
    @PathSensitive(PathSensitivity.NONE)
    public abstract RegularFileProperty getBuildFile();

    @OutputDirectory
    public abstract DirectoryProperty getOutputDir();

    @TaskAction
    public void generate() throws IOException
    {
        String pluginName = getPluginName().get();
        String className = toClassName(pluginName) + "Constants";
        String packageName = toPackageName(getProjectGroup().get());

        File outputBase = getOutputDir().get().getAsFile();
        File packageDir = packageName.isEmpty() ? outputBase : new File(outputBase, packageName.replace('.', '/'));
        Files.createDirectories(packageDir.toPath());

        File outputFile = new File(packageDir, className + ".java");

        try (PrintWriter w = new PrintWriter(outputFile))
        {
            w.println("// Auto-generated by SpellscrollGradle plugin — do not edit");
            if (!packageName.isEmpty())
            {
                w.println("package " + packageName + ";");
                w.println();
            }
            w.println("public final class " + className + " {");
            w.println();
            w.println("    public static final String PLUGIN_ID = \"" + escape(getPluginId().get()) + "\";");
            w.println("    public static final String PLUGIN_VERSION = \"" + escape(getPluginVersion().get()) + "\";");
            w.println("    public static final String PLUGIN_NAME = \"" + escape(pluginName) + "\";");
            w.println();
            w.println("    private " + className + "() {}");
            w.println("}");
        }

        getLogger().lifecycle("Generated {}", outputFile.getAbsolutePath());
    }

    private static String toClassName(String name)
    {
        StringBuilder sb = new StringBuilder();
        boolean capNext = true;
        for (char c : name.toCharArray())
        {
            if (Character.isLetterOrDigit(c))
            {
                sb.append(capNext ? Character.toUpperCase(c) : c);
                capNext = false;
            }
            else capNext = true;
        }
        return sb.toString();
    }

    private static String toPackageName(String group)
    {
        if (group == null || group.isEmpty() || "unspecified".equals(group)) return "";
        return group.toLowerCase().replaceAll("[^a-z0-9._]", "");
    }

    private static String escape(String value) { return value.replace("\\", "\\\\").replace("\"", "\\\""); }
}
