plugins {
    id 'java-gradle-plugin'
    id 'com.gradle.plugin-publish' version '2.1.1'
}

version = "1.1.2"
group = "app.spellscroll"

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.microsoft:credential-secure-storage:1.0.3'
}

gradlePlugin {
    website = "https://spellscroll.app"
    vcsUrl = "https://github.com/Reyzerbit/Spellscroll-Gradle-Plugin"
    plugins {
        register('spellscrollGradle') {
            id = 'app.spellscroll.dev'
            displayName = 'Spellscroll Gradle Plugin'
            description = 'A Gradle plugin for developing Spellscroll plugins. It wires up the Spellscroll API dependency, generates a constants class, builds your optional UI module, and launches the installed Spellscroll app with your plugin loaded for live development.'
            tags.set(['sdk', 'extensions', 'ttrpg', 'plugins', 'spellscroll', 'modding'])
            implementationClass = 'app.spellscroll.SpellscrollGradlePlugin'
        }
    }
}